<a href="https://colab.research.google.com/github/LimGuenTaek/pymldg-rev/blob/main/01_%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EA%B8%B0%EB%B0%98%EC%9D%98%20%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%EA%B3%BC%20%EC%83%9D%ED%83%9C%EA%B3%84%20%EC%9D%B4%ED%95%B4/1_3_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이(Numpy)

* 머신러닝의 주요 알고리즘은 선형대수와 통계등에 기반합니다.

* 특히 선형대수는 수학뿐만 아니라 다른 영역의 자연과학 , 공학에서 널리 사용되고 있습니다.

* Numerical Python을 의미하는 넘파이(Numpy)는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지 입니다.

* 루프를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보장합니다.

* 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있음은 물론이고 , 이들 알고리즘의 입력 데이터와 출력 데이터를 넘파이 배열 타입으로 사용하고 있습니다.


## 넘파이 ndarray 개요

In [1]:
import numpy as np

* 보통 as np를 추가해 약어로 모듈을 표현해주는 것이 관례입니다.

*   항목 추가
*   항목 추가


* 넘파이 기반 데이터 타입은 ndarray입니다. ndarray를 이용해 넘파이에서 다차원(Multi-dimension) 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있습니다.

In [2]:
array1=np.array([1,2,3])

array2=np.array([[1,2,3],
                [4,5,6]])

array3=np.array([[1,2,3]])

print("array1의 shape : {}".format(array1.shape)) # ndarray.shape을 이용해 차원과 크기확인

print("array2의 shape : {}".format(array2.shape))

print("array3의 shape : {}".format(array3.shape))

array1의 shape : (3,)
array2의 shape : (2, 3)
array3의 shape : (1, 3)


* **np.array()**의 사용법은 매우 간단합니다. ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환합니다.

* **ndarray.shape**는 ndarray의 차원과 크기를 튜플(tuple) 형태로 나타내 줍니다.

* array1 과 array3의 데이터는 비슷해 보이지만 차이가 있습니다.
    * array1 : 1차원 array로 3개의 데이터를 가지고 있음
    * array3 : 1개의 row와 3개의 colum을 가지는 2차원 데이터를 가지고 있음

* **이러한 차이를 이해하는 것은 매우 중요합니다. 머신러닝 알고리즘 데이터 세트 간의 입출력과 변환을 수행하다 보면 명확히 1차원 데이터 또는 다차원 데이터를 요구하는 경우가 있습니다.**

* 데이터 값으로는 서로 동일하나 차원이 달라서 오류가 발생하는 경우가 종종 있으므로 이러한 차이를 인지하고 있어야 합니다.

* 이제 각 array의 차원을 **ndarray.ndim**을 이용해 확인해 보겠습니다.

In [3]:
print('array1 : {}차원 ,array2 : {}차원 ,array3 : {}차원'.format(array1.ndim,array2.ndim,array3.ndim)) # ndarray.ndim을 이용해 차원확인

array1 : 1차원 ,array2 : 2차원 ,array3 : 2차원


## ndarray의 데이터 타입

* ndarray내의 데이터값은 숫자,문자열,boolean 모두 가능합니다.

* **ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능합니다.** 즉 , 한개의 ndarray 객체에 int와 float가 함께 있을 수 없습니다.

* ndarray내의 데이터 타입은 **ndarray.dtype** 속성으로 확인할 수 있습니다.

In [4]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype) ## ndarray.dtype 을 통해 데이터 타입 확인

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64



* 서로 다른 데이터 타입을 가질 수 있는 리스트와는 다르게 ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다고 했는데,

* 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 **큰 데이터 타입으로 형 변환을 일괄 적용합니다.**

In [5]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


* **ndarray 내 데이터값의 타입 변경도 astype()** 메서드를 이용해 할 수 있습니다.

* astype()에 인자로 원하는 타입을 문자열로 지정하면 됩니다.

* 이렇게 데이터 타입을 변경하는 경우는 **대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되는데 , 메모리를 더 절약해야 할 때 보통 이용됩니다.**

In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

[1. 2. 3.] float64



## ndarray를 편리하게 생성하기 - **arange** , **zeros** , **ones**

* 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우가 발생할 수 있습니다.

* 이 경우 **arange() , zeros() , ones()**를 이용해 쉽게 ndarray를 생성할 수 있습니다.

* 주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용됩니다.

* zeros() , ones() 는 **함수 인자로 튜플 형태의 shape** 값을 입력하면 됩니다. 함수 인자로 dtype을 정해주지 않으면 default로 float64 형의 데이터로 ndarray를 채웁니다.

In [ ]:
sequence_array=np.arange(1,10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

zero_array=np.zeros((3,2))
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[1 2 3 4 5 6 7 8 9]
int64 (9,)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 **reshape()**

* **reshape()** 메소드는 ndarray를 특정 차원 및 크기로 변환합니다.

* **변환을 원하는 크기를 함수 인자로** 부여하면 됩니다.

* 당연한 얘기지만 , reshape()는 지정된 사이즈로 변경이 불가능하면 오류를 발생합니다. 가령 (10,) 데이터를 (4,3) Shape 형태로 변경할 수는 없습니다.

* reshape()를 실전에서 더욱 효율적으로 사용하는 경우는 아마도 인자로 -1을 적용하는 경우일 것입니다.

* -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해 줍니다.

In [ ]:
array1=np.arange(10)

print(array1,end='\n\n')

print(array1.reshape(2,5),end='\n\n')

print(array1.reshape(5,2),end='\n\n')

print(array1.reshape(2,-1),end='\n\n')

print(array1.reshape(-1,2),end='\n\n')

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]



## 넘파이의 ndarray의 데이터 세트 선택하기 - **인덱싱(Indexing)**

* **단일 값 추출** : 1개의 데이터 값을 선택하려면 ndarray 객체에 해당하는 위치의 인덱스 값을 [ ]안에 입력하면 됩니다.

  * 인덱스는 앞에서 부터 시작할 때는 0부터 시작하며
  * 인덱스는 뒤에서 부터 시작할 때는 -1로 시작합니다.
  * 다차원 배열의 추출은 array[idx1,idx2,idx3...] 이런식으로 접근하면 됩니다.

* **슬라이싱** :  '__:__ '기호를 이용해 데이터를 슬라이싱 해서 추출할 수 있습니다.

  * array[0:3] : idx 0 ~ 2 까지 데이터 추출
  * array[0:3 , 0:3] : row idx 0 ~ 2 까지 데이터 추출 , col idx 0 ~ 2 까지 데이터 추출
  * ':' 기호 앞에 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
  * ':' 기호 뒤에 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주

* **팬시 인덱싱** : 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식 

* **불린 인덱싱** : Boolean Indexing은 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식입니다.

#### **팬시 인덱싱**

* **리스트나 ndarray로 인덱스 집합을 지정하면** 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

* 2차원 ndarray에 팬시 인덱싱을 적용하면서 이 기능이 어떻게 동작하는지 살펴보겠습니다.

In [ ]:
array1d=np.arange(1,10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2] # [0,2] , [1,2]에 해당되는 [3 6] 반환

array4=array2d[[0,1],0:2] # [0,0] , [0,1] , [1,0] , [1,1]에 해당되는 값들 반환

array5=array2d[[0,1]] # [0:],[1:]에 해당되는 값들 반환

print(array3)
print(array4)
print(array5)

[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


#### **불린 인덱싱**

* 불린 인덱싱(Boolean indexing)은 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식

* 불린 인덱싱은 ndarray의 인덱스를 지정하는 [  ] 내에 조건문을 그대로 기재하기만 하면 됨

In [ ]:
array1d = np.arange(1,10)
array3=array1d[array1d>5]
print("array1d > 5 불린 인덱싱 결과 : {}".format(array3))
print(array1d>5)

array1d > 5 불린 인덱싱 결과 : [6 7 8 9]
[False False False False False  True  True  True  True]


## 행렬의 정렬 - sort()와 argsort()

### 행렬 정렬

* 넘파이에서 행렬을 정렬하는 대표적인 방법인 **np.sort()**와 **ndarray.sort()** , 그리고 정렬된 행렬의 인덱스를 반환하는 argsort()에 대해서 알아보겠습니다.

* 넘파이의 행렬 정렬은 np.sort()와 같은 넘파이에서 sort()를 호출하는 방식과 ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식이 있습니다.

  * **np.sort()**의 경우 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환합니다.

  * **ndarray.sort()**는 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None 입니다.

In [ ]:
org_array=np.array([3,1,9,5])

sort_array1=np.sort(org_array) # 정렬된 배열을 반환

org_array.sort() # 배열 자체를 정렬 시킴

print(sort_array1)
print(org_array)

[1 3 5 9]
[1 3 5 9]


In [ ]:
array2d=np.array([[8,12],
                  [7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0) # row 방향으로 정렬

sort_array2d_axis1=np.sort(array2d,axis=1) # colum 방향으로 정렬

print(sort_array2d_axis0)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


### 정렬된 행렬의 인덱스를 반환하기

* 원본 행렬이 정렬되었을 때 **기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용합니다.**

* **np.argsort()**는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환합니다.


In [ ]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 행렬의 인덱스 : {}".format(sort_indices))

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 : [1 0 3 2]


* **argsort()는 넘파이에서 매우 활용도가 높습니다.**

* 넘파이의 ndarray는 RDBMS의 TABLE 칼럼이나 뒤에 소개할 Pandas DataFrame 칼럼과 같은 메타 데이터를 가질 수 없습니다.

* 따라서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야만 합니다.

* 예를 들어 학생별 시험 성적을 데이터로 표현하기 위해서는 학생의 이름과 시험 성적을 각각 ndarray로 가져야 합니다.(2개의 ndarray가 필요)

* 이 때 시험 성적순으로 학생 이름을 출력하고자 한다면 np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출할 수 있으며 , 이러한 방식은 넘파이의 데이터 추출에서 많이 사용됩니다.

In [ ]:
name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)

print('성적 오름차순으로 name 출력 : {}'.format(name_array[sort_indices_asc]))

성적 오름차순으로 name 출력 : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

* 넘파이는 매우 다양한 선형대수 연산을 지원합니다.

* 그중 가장 많이 사용되면서도 기본 연산인 **행렬 내적**과 **전치 행렬**을 구하는 방법을 알아보겠습니다.

### 행렬 내적
* 행렬 내적(행렬 곱) : 두 행렬 A와 B의 내적은 **np.dot()**을 이용해 계산이 가능합니다.

In [ ]:
A=np.array([[1,2,3],
            [4,5,6]])

B=np.array([[7,8],
            [9,10],
            [11,12]])

C=np.dot(A,B)

print(C)

[[ 58  64]
 [139 154]]


### 전치 행렬
* 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬이라고 합니다.

* **np.transepose()**를 이용해 전치 행렬을 쉽게 구할 수 있습니다.

In [ ]:
A=np.array([[1,2,3],
            [4,5,6]])

A_t=np.transpose(A)

print(A_t)

[[1 4]
 [2 5]
 [3 6]]


# Method 정리

#### 1. np.ndarray()

#### 2. ndarray.shape

#### 3. ndarray.ndim

#### 4. ndarray.dtype

#### 5. ndarray.astype('dtype')

#### 6. np.arange(tuple) , np.zeros(tuple) , np.ones(tuple) , default = float64

#### 7. ndarray.reshape(tuple)

#### 8. np.sort(ndarray) , ndarray.sort()

#### 9. np.argsort(ndarray)

#### 10. np.dot(ndarray1 , ndarray2)

#### 11. np.transpose(ndarray)